### PR TITLE
Update twig filter namespace and symplify logic by default

### PR DESCRIPTION
**Pull request by clubdesarrolladores**
Please add a tag on merge, thanks.

### CODE REVIEW

**Comment by ryanhalliday** [comment]
Hi cid,

Thanks for your PR. 
Could you also bump the version requirement in `composer.json` as this will not be compatible with Twig 1.12.

This project existed before the `TwigFilter` class existed so are you able to find the version it was introduced and use that for the `>=` requirement?

Thanks

**Comment by clubdesarrolladores** [comment]
twig/twig v3.0.0 requires php ^7.2.9

**Comment by ryanhalliday** [comment]
Not sure 3.0 is the best choice after a bit of research sorry - its not even a month old and TwigFilter existed in 2.x with `SimpleFilter` being deprecated in 2.7 from what I can see: https://github.com/twigphp/Twig/blob/379f0c3553fcc3b4ebd0bc56e48036fa85bfdbbb/lib/Twig/SimpleFilter.php#L19

Could you use 2.7 instead? Gives us some 2.x compatibility for this library. 

Thanks!

**Comment by clubdesarrolladores** [comment]
Ok! Twig 2.7

Thanks man!

**Comment by ryanhalliday** [comment]
Sweet as, thanks for this. I'll do some testing ASAP and tag a release

**Comment by ryanhalliday** [comment]
FYI there is now a pre-release tag in case you wanted to use that. If you set that in your `composer.json` when I do an actual `4.0.0` it will hopefully update on your next `composer update`

**Comment by clubdesarrolladores** [comment]
Thank you, i really appreciate it.

**Pull request merged**
